server {
    listen 80;
    server_name _;

    root /srv/data;
    autoindex off;

    error_page 404 /404.html;

    location = / {
        alias /srv/pages/;
        try_files /hello.html =404;
    }

    location / {
        try_files $uri =404;
    }

    location = /404.html {
        root /srv/pages;
        internal;
    }
}
